repos:
  - repo: local
    hooks:
      - id: pre-commit-checks
        name: Pre-commit checks
        entry: ./tests/scripts/pre-commit.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
